### ISSUE TITLE
tutorial_pearson_residuals: why are residuals computed twice? 

### ISSUE THREAD

**Issue by alexlenail** [scverse/scanpy-tutorials#57]
In the tutorial_pearson_residuals tutorial, the steps are: 

```
# sets adata.var["highly_variable"]
sc.experimental.pp.highly_variable_genes(adata, flavor="pearson_residuals", n_top_genes=2000) 
```
```
adata = adata[:, adata.var["highly_variable"]]
```
```
sc.experimental.pp.normalize_pearson_residuals(adata)
```

`sc.experimental.pp.highly_variable_genes(flavor="pearson_residuals")` computes pearson residuals here: 

https://github.com/scverse/scanpy/blob/2e98705347ea484c36caa9ba10de1987b09081bf/scanpy/experimental/pp/_highly_variable_genes.py#L120-L127

And `sc.experimental.pp.normalize_pearson_residuals` computes pearson residuals here: 

https://github.com/scverse/scanpy/blob/2e98705347ea484c36caa9ba10de1987b09081bf/scanpy/experimental/pp/_normalization.py#L130

which refers to

https://github.com/scverse/scanpy/blob/2e98705347ea484c36caa9ba10de1987b09081bf/scanpy/experimental/pp/_normalization.py#L57-L64

So if I'm understanding, the tutorial leads you to compute pearson residuals twice, which is a little confusing. Why are there two different functions for computing those residuals anyhow? @jlause

**Comment by jlause** [comment]
Hi Alex,

correct, residuals are computed twice. The two functions you mention have slightly different ways of computing them though:

- `normalize_pearson_residuals` computes all residuals at once and outputs the full residual matrix. This requires a lot of memory because the matrix of residuals is dense, so we only recommend to do it after gene selection.
- `highly_variable_genes(flavor="pearson_residuals")` computes residual variance for each gene and performs a gene selection. To do so without needing to have the full dense residual matrix in memory, we iterate over (batches of) genes, compute residuals for this subset of genes, obtain their residual variance, drop the residual matrix of the batch and move on to the next one.

The use-case we had in mind was that of a large dataset with ~millions of cells, which (at least in our computing environment) required batch-wise gene selection before one could work on the residual matrix and do PCA and further processing. So in that case, one has to compute residuals twice, because in the first time, it is not clear yet which features one wants to keep.

Regarding the code, I agree that it is not optimal to have to places where essentially the same computation happens. Maybe we can update

-  https://github.com/scverse/scanpy/blob/2e98705347ea484c36caa9ba10de1987b09081bf/scanpy/experimental/pp/_normalization.py#L48-L62
and
- https://github.com/scverse/scanpy/blob/2e98705347ea484c36caa9ba10de1987b09081bf/scanpy/experimental/pp/_highly_variable_genes.py#L110-L127
in a way that both use the same shared function(s) to compute the residuals, such that there is only one place where that happens.. CCing @giovp and @ivirshup on this.

Let me know what you think and if this addresses your question!
