### ISSUE TITLE
Finalize linking strategy (where to host, where to link)

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scanpy-tutorials#64]
e.g: Remove everything but the tutorials shown on scanpy docs from this repo and render them from within the scanpy docs

**Comment by flying-sheep** [comment]
PR builds should also work, so we should leave CI, and change conf.py and friends to use myst-nb

**Comment by grst** [comment]
I'm not entirely sure what the canonical location should be. 

 * In an ideal world, the tutorials would live in the scanpy repo itself, and were executed on each documentation build. That way we'd make sure that they are never outdated to a point that they are incompatible with the latest released version. 
 * In practice, this doesn't work out, because running tutorials exhausts CI resources, and storing them in the main git repo makes it way too bulky. 

The easy way out is to keep them completely separate on scanpy-tutorials, and just link them from both the scanpy documentation and scverse.org/learn. By keeping them in the main scanpy docs and setting up some sort of synchronization (as in https://github.com/scverse/scanpy-tutorials/issues/69), we'd be better prepared if at some point in the future we end up having the CI resources (e.g. AWS runners) to execute tutorials as part of the tests. 

I'm fine either way, but we should indeed make sure that the tutorials only live in one location and the others link to it.

**Comment by flying-sheep** [comment]
There’s also stuff like this: https://github.com/scverse/scanpy/pull/923

**Comment by grst** [comment]
I think it's easiest to keep the tutorials entirely separate and just link them from the main docs (and scverse.org/learn, where appropriate)

**Comment by flying-sheep** [comment]
That’s a fine solution for me to.

The only minor disadvantage is that when something gets renamed, links are broken until scanpy’s CI has noticed us that that’s the case. Which it luckily does again now that I reverted that being broken in #2220.
